;; The first three lines of this file were inserted by DrRacket. They record metadata
;; about the language level of this file in a form that our tools can easily process.
#reader(lib "htdp-intermediate-lambda-reader.ss" "lang")((modname Exercise_441) (read-case-sensitive #t) (teachpacks ((lib "abstraction.rkt" "teachpack" "2htdp") (lib "image.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp"))) (htdp-settings #(#t quasiquote repeating-decimal #f #t none #f ((lib "abstraction.rkt" "teachpack" "2htdp") (lib "image.rkt" "teachpack" "2htdp") (lib "batch-io.rkt" "teachpack" "2htdp") (lib "universe.rkt" "teachpack" "2htdp")) #f)))
; [List-of Number] -> [List-of Number]
; produces a sorted version of alon
; assume the numbers are all distinct
(check-expect (quick-sort< '(11 9 2 18 12 14 4 1)) '(1 2 4 9 11 12 14 18))
(check-expect (quick-sort< '(11 9 2 18 4 12 14 4 12 1)) '(1 2 4 4 9 11 12 12 14 18))
(check-expect (quick-sort< '(11)) '(11))
(define (quick-sort< alon)
  (cond
    [(empty? alon) '()]
    [(empty? (rest alon)) alon]
    [else (local ((define pivot (first alon)))
            (append (quick-sort< (smallers (rest alon) pivot))
                    (list pivot)
                    (quick-sort< (not-smallers (rest alon) pivot))))]))

; [List-of Number] Number -> [List-of Number]
; returns list that contains element that are smaller than given number only
(define (smallers alon n)
  (filter (lambda (x) (< x n)) alon))

; [List-of Number] Number -> [List-of Number]
; returns list that contains element that are not smaller than given number only
(define (not-smallers alon n)
  (filter (lambda (x) (>= x n)) alon))

(quick-sort< (list 10 6 8 9 14 12 3 11 14 16 2))
==
(append (quick-sort< '(6 8 9 3 2))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append (append (quick-sort< '(3 2))
                '(6)
                (quick-sort< '(8 9)))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append (append (append (quick-sort< '(2))
                        '(3)
                        (quick-sort< '()))
                '(6)
                (quick-sort< '(8 9)))
        '(10)
        (quick-sort< '(14 12 11 14 16)))

==
(append (append (append '(2)
                        '(3)
                        (quick-sort< '()))
                '(6)
                (quick-sort< '(8 9)))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append (append (append '(2)
                        '(3)
                        '())
                '(6)
                (quick-sort< '(8 9)))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append (append '(2 3)
                '(6)
                (quick-sort< '(8 9)))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append (append '(2 3)
                '(6)
                (append (quick-sort< '())
                        '(8)
                        (quick-sort< '(9))))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append (append '(2 3)
                '(6)
                (append '()
                        '(8)
                        (quick-sort< '(9))))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append (append '(2 3)
                '(6)
                (append '()
                        '(8)
                        '(9)))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append (append '(2 3)
                '(6)
                '(8 9))
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append '(2 3 6 8 9)
        '(10)
        (quick-sort< '(14 12 11 14 16)))
==
(append '(2 3 6 8 9)
        '(10)
        (append (quick-sort< '(12 11))
                '(14)
                (quick-sort< '(14 16))))
==
(append '(2 3 6 8 9)
        '(10)
        (append (append (quick-sort< '(11))
                        '(12)
                        (quick-sort< '()))
                '(14)
                (quick-sort< '(14 16))))
==
(append '(2 3 6 8 9)
        '(10)
        (append (append '(11)
                        '(12)
                        (quick-sort< '()))
                '(14)
                (quick-sort< '(14 16))))
==
(append '(2 3 6 8 9)
        '(10)
        (append (append '(11)
                        '(12)
                        '())
                '(14)
                (quick-sort< '(14 16))))
==
(append '(2 3 6 8 9)
        '(10)
        (append '(11 12)
                '(14)
                (quick-sort< '(14 16))))
==
(append '(2 3 6 8 9)
        '(10)
        (append '(11 12)
                '(14)
                (append (quick-sort< '())
                        '(14)
                        (quick-sort '(16)))))
==
(append '(2 3 6 8 9)
        '(10)
        (append '(11 12)
                '(14)
                (append '()
                        '(14)
                        (quick-sort '(16)))))
==
(append '(2 3 6 8 9)
        '(10)
        (append '(11 12)
                '(14)
                (append '()
                        '(14)
                        '(16))))
==
(append '(2 3 6 8 9)
        '(10)
        (append '(11 12)
                '(14)
                '(14 16)))
==
(append '(2 3 6 8 9)
        '(10)
        '(11 12 14 14 16))
==
'(2 3 6 8 9 10 11 12 14 14 16)

=====================================================================================

(quick-sort< (list 1 2 3 4 5 6 7 8 9 10 11 12 13 14))
==
(append (quick-sort< '())
        '(1)
        (quick-sort< '(2 3 4 5 6 7 8 9 10 11 12 13 14)))
==
(append '()
        '(1)
        (quick-sort< '(2 3 4 5 6 7 8 9 10 11 12 13 14)))
==
(append '()
        '(1)
        (append (quick-sort< '())
                '(2)
                (quick-sort< '(3 4 5 6 7 8 9 10 11 12 13 14))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (quick-sort< '(3 4 5 6 7 8 9 10 11 12 13 14))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append (quick-sort< '())
                        '(3)
                        (quick-sort< '(4 5 6 7 8 9 10 11 12 13 14)))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (quick-sort< '(4 5 6 7 8 9 10 11 12 13 14)))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append (quick-sort< '())
                                '(4)
                                (quick-sort< '(5 6 7 8 9 10 11 12 13 14))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (quick-sort< '(5 6 7 8 9 10 11 12 13 14))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append (quick-sort< '())
                                        '(5)
                                        (quick-sort< '(6 7 8 9 10 11 12 13 14)))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (quick-sort< '(6 7 8 9 10 11 12 13 14)))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append (quick-sort< '())
                                                '(6)
                                                (quick-sort< '(7 8 9 10 11 12 13 14))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (quick-sort< '(7 8 9 10 11 12 13 14))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append (quick-sort< '())
                                                        '(7)
                                                        (quick-sort< '(8 9 10 11 12 13 14)))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (quick-sort< '(8 9 10 11 12 13 14)))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append (quick-sort< '())
                                                                '(8)
                                                                (quick-sort< '(9 10 11 12 13 14))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (quick-sort< '(9 10 11 12 13 14))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append (quick-sort< '())
                                                                        '(9)
                                                                        (quick-sort< '(10 11 12 13 14)))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (quick-sort< '(10 11 12 13 14)))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append (quick-sort< '())
                                                                                '(10)
                                                                                (quick-sort< '(11 12 13 14))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (quick-sort< '(11 12 13 14))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (append (quick-sort< '())
                                                                                        '(11)
                                                                                        (quick-sort< '(12 13 14)))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (append '()
                                                                                        '(11)
                                                                                        (quick-sort< '(12 13 14)))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (append '()
                                                                                        '(11)
                                                                                        (append (quick-sort< '())
                                                                                                '(12)
                                                                                                (quick-sort< '(13 14))))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (append '()
                                                                                        '(11)
                                                                                        (append '()
                                                                                                '(12)
                                                                                                (quick-sort< '(13 14))))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (append '()
                                                                                        '(11)
                                                                                        (append '()
                                                                                                '(12)
                                                                                                (append (quick-sort< '())
                                                                                                        '(13)
                                                                                                        (quick-sort< '(14)))))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (append '()
                                                                                        '(11)
                                                                                        (append '()
                                                                                                '(12)
                                                                                                (append '()
                                                                                                        '(13)
                                                                                                        (quick-sort< '(14)))))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (append '()
                                                                                        '(11)
                                                                                        (append '()
                                                                                                '(12)
                                                                                                (append '()
                                                                                                        '(13)
                                                                                                        '(14))))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (append '()
                                                                                        '(11)
                                                                                        (append '()
                                                                                                '(12)
                                                                                                '(13 14)))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                (append '()
                                                                                        '(11)
                                                                                        '(12 13 14))))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        (append '()
                                                                                '(10)
                                                                                '(11 12 13 14)))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                (append '()
                                                                        '(9)
                                                                        '(10 11 12 13 14))))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        (append '()
                                                                '(8)
                                                                '(9 10 11 12 13 14)))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                (append '()
                                                        '(7)
                                                        '(8 9 10 11 12 13 14))))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        (append '()
                                                '(6)
                                                '(7 8 9 10 11 12 13 14)))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                (append '()
                                        '(5)
                                        '(6 7 8 9 10 11 12 13 14))))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        (append '()
                                '(4)
                                '(5 6 7 8 9 10 11 12 13 14)))))
==
(append '()
        '(1)
        (append '()
                '(2)
                (append '()
                        '(3)
                        '(4 5 6 7 8 9 10 11 12 13 14))))
==
(append '()
        '(1)
        (append '()
                '(2)
                '(3 4 5 6 7 8 9 10 11 12 13 14)))
==
(append '()
        '(1)
        '(2 3 4 5 6 7 8 9 10 11 12 13 14))
==
'(1 2 3 4 5 6 7 8 9 10 11 12 13 14)